from core.game.entities.EntityState.state import *

player_states = {
            PLAYER_INTENT_STATE.IDLE: [PLAYER_INTENT_STATE.UP,PLAYER_INTENT_STATE.LEFT,PLAYER_INTENT_STATE.RIGHT,PLAYER_INTENT_STATE.DOWN,PLAYER_INTENT_STATE.ATTACK,PLAYER_INTENT_STATE.BLOCK],
            PLAYER_INTENT_STATE.UP: [PLAYER_INTENT_STATE.IDLE,PLAYER_INTENT_STATE.LEFT,PLAYER_INTENT_STATE.RIGHT,PLAYER_INTENT_STATE.DOWN,PLAYER_INTENT_STATE.ATTACK,PLAYER_INTENT_STATE.BLOCK],
            PLAYER_INTENT_STATE.LEFT: [PLAYER_INTENT_STATE.IDLE,PLAYER_INTENT_STATE.UP,PLAYER_INTENT_STATE.RIGHT,PLAYER_INTENT_STATE.DOWN,PLAYER_INTENT_STATE.ATTACK,PLAYER_INTENT_STATE.BLOCK],
            PLAYER_INTENT_STATE.RIGHT: [PLAYER_INTENT_STATE.IDLE,PLAYER_INTENT_STATE.UP,PLAYER_INTENT_STATE.LEFT,PLAYER_INTENT_STATE.DOWN,PLAYER_INTENT_STATE.ATTACK,PLAYER_INTENT_STATE.BLOCK],
            PLAYER_INTENT_STATE.DOWN: [PLAYER_INTENT_STATE.IDLE,PLAYER_INTENT_STATE.UP,PLAYER_INTENT_STATE.LEFT,PLAYER_INTENT_STATE.RIGHT,PLAYER_INTENT_STATE.ATTACK,PLAYER_INTENT_STATE.BLOCK],
            PLAYER_INTENT_STATE.ATTACK: [PLAYER_INTENT_STATE.IDLE,PLAYER_INTENT_STATE.UP,PLAYER_INTENT_STATE.LEFT,PLAYER_INTENT_STATE.RIGHT,PLAYER_INTENT_STATE.DOWN,PLAYER_INTENT_STATE.BLOCK],
            PLAYER_INTENT_STATE.BLOCK: [PLAYER_INTENT_STATE.IDLE,PLAYER_INTENT_STATE.UP,PLAYER_INTENT_STATE.LEFT,PLAYER_INTENT_STATE.RIGHT,PLAYER_INTENT_STATE.DOWN,PLAYER_INTENT_STATE.ATTACK]
        }