# redundant trash from this experiment.
# this was generated by GPT 3.5.
# yes it is redundant.
# i really should centralize colors, but I can't decide if I want to make games or an engine
# like I'm kind of bordering on engine but i have no engine. I have some nice tools though, althought I should improve the UI.
# The sprite editor system i'm going to add should take the place of junk like this.
# this framework is kind of everywhere


white = (255,255,255)
black = (0,0,0)
red = (255,0,0)
green = (0,255,0)
blue = (0,0,255)
yellow = (255,255,0)
cyan = (0,255,255)
purple = (255,0,255)

light_pink = (255,153,255)
dark_pink = (255,51,153)
orange = (255,165,0)
dark_orange = (255,140,0)
gold = (255,215,0)
lime = (50,205,50)
dark_green = (0,100,0)
forest_green = (34,139,34)

light_blue = (173,216,230)
sky_blue = (135,206,235)
deep_sky_blue = (0,191,255)
navy = (0,0,128)
teal = (0,128,128)
turquoise = (64,224,208)
aqua = (127,255,212)
indigo = (75,0,130)

violet = (138,43,226)
lavender = (230,230,250)
plum = (221,160,221)
maroon = (128,0,0)
crimson = (220,20,60)
salmon = (250,128,114)
coral = (255,127,80)
tomato = (255,99,71)

brown = (165,42,42)
saddle_brown = (139,69,19)
chocolate = (210,105,30)
tan = (210,180,140)
beige = (245,245,220)
olive = (128,128,0)
dark_olive = (85,107,47)
khaki = (240,230,140)

silver = (192,192,192)
gray = (128,128,128)
dark_gray = (64,64,64)
light_gray = (211,211,211)
snow = (255,250,250)
ivory = (255,255,240)
mint = (189,252,201)
spring_green = (0,255,127)

hot_pink = (255,105,180)
deep_pink = (255,20,147)
orchid = (218,112,214)
medium_purple = (147,112,219)
royal_blue = (65,105,225)
steel_blue = (70,130,180)
sea_green = (46,139,87)
earth = [
    blue,
    green
]

vertex_debug_colors = [
    (255, 0, 0),     # vertex 0 - red
    (0, 255, 0),     # vertex 1 - green
    (0, 0, 255),     # vertex 2 - blue
    (255, 255, 0),   # vertex 3 - yellow
    (255, 0, 255),   # vertex 4 - magenta
    (0, 255, 255),   # vertex 5 - cyan
    (255, 128, 0),   # vertex 6 - orange
    (128, 0, 255),   # vertex 7 - purple
]

face_colors = [
    (255,255,255),  # white
    (0,0,0),        # black
    (255,0,0),      # red
    (0,255,0),      # green
    (0,0,255),      # blue
    (255,255,0),    # yellow
    (0,255,255),    # cyan
    (255,0,255),    # purple
    (255,153,255),  # light_pink
    (255,51,153),   # dark_pink
    (255,165,0),    # orange
    (255,140,0),    # dark_orange
    (255,215,0),    # gold
    (50,205,50),    # lime
    (0,100,0),      # dark_green
    (34,139,34),    # forest_green
    (173,216,230),  # light_blue
    (135,206,235),  # sky_blue
    (0,191,255),    # deep_sky_blue
    (0,0,128),      # navy
    (0,128,128),    # teal
    (64,224,208),   # turquoise
    (127,255,212),  # aqua
    (75,0,130),     # indigo
    (138,43,226),   # violet
    (230,230,250),  # lavender
    (221,160,221),  # plum
    (128,0,0),      # maroon
    (220,20,60),    # crimson
    (250,128,114),  # salmon
    (255,127,80),   # coral
    (255,99,71),    # tomato
    (165,42,42),    # brown
    (139,69,19),    # saddle_brown
    (210,105,30),   # chocolate
    (210,180,140),  # tan
    (245,245,220),  # beige
    (128,128,0),    # olive
    (85,107,47),    # dark_olive
    (240,230,140),  # khaki
    (192,192,192),  # silver
    (128,128,128),  # gray
    (64,64,64),     # dark_gray
    (211,211,211),  # light_gray
    (255,250,250),  # snow
    (255,255,240),  # ivory
    (189,252,201),  # mint
    (0,255,127),    # spring_green
    (255,105,180),  # hot_pink
    (255,20,147)    # deep_pink
]