# redundant trash from this experiment.
# this was generated by GPT 3.5.
# yes it is redundant.
# i really should centralize colors, but I can't decide if I want to make games or an engine
# like I'm kind of bordering on engine but i have no engine. I have some nice tools though, althought I should improve the UI.
# The sprite editor system i'm going to add should take the place of junk like this.
# this framework is kind of everywhere


white = (255, 255, 255, 255)
black = (0, 0, 0, 255)
red = (255, 0, 0, 255)
green = (0, 255, 0, 255)
blue = (0, 0, 255, 255)
yellow = (255, 255, 0, 255)
cyan = (0, 255, 255, 255)
purple = (255, 0, 255, 255)

light_pink = (255, 153, 255, 255)
dark_pink = (255, 51, 153, 255)
orange = (255, 165, 0, 255)
dark_orange = (255, 140, 0, 255)
gold = (255, 215, 0, 255)
lime = (50, 205, 50, 255)
dark_green = (0, 100, 0, 255)
forest_green = (34, 139, 34, 255)

light_blue = (173, 216, 230, 255)
sky_blue = (135, 206, 235, 255)
deep_sky_blue = (0, 191, 255, 255)
navy = (0, 0, 128, 255)
teal = (0, 128, 128, 255)
turquoise = (64, 224, 208, 255)
aqua = (127, 255, 212, 255)
indigo = (75, 0, 130, 255)

violet = (138, 43, 226, 255)
lavender = (230, 230, 250, 255)
plum = (221, 160, 221, 255)
maroon = (128, 0, 0, 255)
crimson = (220, 20, 60, 255)
salmon = (250, 128, 114, 255)
coral = (255, 127, 80, 255)
tomato = (255, 99, 71, 255)

brown = (165, 42, 42, 255)
saddle_brown = (139, 69, 19, 255)
chocolate = (210, 105, 30, 255)
tan = (210, 180, 140, 255)
beige = (245, 245, 220, 255)
olive = (128, 128, 0, 255)
dark_olive = (85, 107, 47, 255)
khaki = (240, 230, 140, 255)

silver = (192, 192, 192, 255)
gray = (128, 128, 128, 255)
dark_gray = (64, 64, 64, 255)
light_gray = (211, 211, 211, 255)
snow = (255, 250, 250, 255)
ivory = (255, 255, 240, 255)
mint = (189, 252, 201, 255)
spring_green = (0, 255, 127, 255)

hot_pink = (255, 105, 180, 255)
deep_pink = (255, 20, 147, 255)
orchid = (218, 112, 214, 255)
medium_purple = (147, 112, 219, 255)
royal_blue = (65, 105, 225, 255)
steel_blue = (70, 130, 180, 255)
sea_green = (46, 139, 87, 255)

earth = [
    blue,
    green
]

vertex_debug_colors = [
    (255, 0, 0, 255),
    (0, 255, 0, 255),
    (0, 0, 255, 255),
    (255, 255, 0, 255),
    (255, 0, 255, 255),
    (0, 255, 255, 255),
    (255, 128, 0, 255),
    (128, 0, 255, 255)
]

face_colors = [
    white,
    black,
    red,
    green,
    blue,
    yellow,
    cyan,
    purple,
    light_pink,
    dark_pink,
    orange,
    dark_orange,
    gold,
    lime,
    dark_green,
    forest_green,
    light_blue,
    sky_blue,
    deep_sky_blue,
    navy,
    teal,
    turquoise,
    aqua,
    indigo,
    violet,
    lavender,
    plum,
    maroon,
    crimson,
    salmon,
    coral,
    tomato,
    brown,
    saddle_brown,
    chocolate,
    tan,
    beige,
    olive,
    dark_olive,
    khaki,
    silver,
    gray,
    dark_gray,
    light_gray,
    snow,
    ivory,
    mint,
    spring_green,
    hot_pink,
    deep_pink
]